name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.x
    - name: Install Ruby dependencies
      run: bundle install
    - name: Install Node.js dependencies
      run: npm install
    - name: Build assets
      run: npm run compile
    - name: Run tests
      run: bundle exec rake
